### ISSUE TITLE
OBJ files missing all colours after conversion to UDS

### ISSUE THREAD

**Issue by CodeWarrior99** [Euclideon/vaultclient#1]
This seems to be an issue with the converter inside of Vault.

The converted OBJ file is stripped of all of its colours and just appears as a white blob.

You then need to turn on edge highlighting just to be able to see any details unfortunately.

The data that I'm working with is LIDAR data that has been meshed inside of CloudCompare and then exported as an OBJ file.

I was able to convert OBJ's to UDS format in Geoverse Convert and they would come through with colours but for some reason the converter in Vault appears to be doing it differently.

The end result looks really bad even with edge highlighting turned on
[LIDAR data of a house.zip](https://github.com/Euclideon/vaultclient/files/3016614/LIDAR.data.of.a.house.zip)

[LIDAR data of a house-uds version.zip](https://github.com/Euclideon/vaultclient/files/3016624/LIDAR.data.of.a.house-uds.version.zip)
![LIDAR data of a house-uds version](https://user-images.githubusercontent.com/42997998/55137867-65399d00-5132-11e9-870a-36c564e7b4a4.png)
![LIDAR data of a house-uds version - edge highlighted](https://user-images.githubusercontent.com/42997998/55137868-65399d00-5132-11e9-96a9-79abcc997e36.png)

.

**Comment by dpev** [comment]
Hi,

Thanks for the thorough bug report! The OBJ you attached has no color or UV information in it:

# Created by CloudCompare v2.10-beta
# Created 3/28/2019 8:03 AM
v 297570.573974609375 6705501.862365722656 18.295120239258
v 297570.252380371094 6705501.866027832031 18.295120239258
...
vn -0.009222226217 0.042012363672 -0.999074518681
vn 0.001016409718 0.041672799736 -0.999130785465
...
g Mesh[32-1-468-146-27.clean] (level 11).part.remaining.clone
f 39//39 38//38 2//2
f 2//2 1//1 39//39

We do support OBJ's with vertex colour information (lines starting with v in the OBJ file will have additional 0-255 numbers after the vertex position), but a texture will give best results (lines starting with f in the OBJ will have a number between the 1st and 2nd / character).

I haven't played with CloudCompare recently enough to offer suggestions on how to export with colour information but at least this is a pointer in the right direction. I'm not sure what went on to get a different result in Geoverse Convert, I wrote the OBJ import on both and neither can get colour information from any other source! :)

Regards

Dave

**Comment by OsiJr** [comment]
@CodeWarrior99, we've added native OBJ rendering support in 0.4.0 to handle these small models where lighting is required and there isn't much benefit from converting to UDS (note that I randomly picked a SRID that had a road nearby).

![image](https://user-images.githubusercontent.com/9654665/67764033-b75dea80-fa94-11e9-854e-9a7868c35c9d.png)

**Comment by CodeWarrior99** [comment]
Excellent! :-)
When will the next version be released?

**Comment by OsiJr** [comment]
We're just finalising most of it now- this is already in master though.

**Comment by OsiJr** [comment]
We are not currently investigating fixing this for conversion to UDS so closing this as its possible to view the OBJ with lighting in Client now.

We will reopen this in future if a model that should be converted to UDS is found and lighting is required.
