### ISSUE TITLE
Ability to collapse / expand the side settings pane quickly with a hot key or mouse click

### ISSUE THREAD

**Issue by CodeWarrior99** [Euclideon/vaultclient#11]
**Is your feature request related to a problem? Please describe.**

It's very slow and annoying to have to re-size the side panel in order to make adjustments to the various options that affect the main window. 

Hovering the mouse cursor over the edge of the panel can also be a bit difficult to get it to show you the "adjustment" arrows.

**Describe the solution you'd like**

Ideally it would be nice to be able just hit an "F" key or some other keyboard combination to cause the right-side panel to fully expand outwards or collapse completely. 
They key would just be a toggle of course.

**Describe alternatives you've considered**

I've seen this used in other software and it's quite handy.

**Additional context**
![Collapse Toggle](https://user-images.githubusercontent.com/42997998/65835872-168cdb80-e2ec-11e9-9aa6-beb6318aac1a.png)

**Comment by OsiJr** [comment]
Hi @CodeWarrior99. Thanks for the suggestion, we've had it before but I can't see it in the tracking system so I've created a new task AB#322 to track this. EVC0.5 is scheduled to be a major amount of UX/UI work (like this task).

In the short term as a workaround, clicking `Windows>Scene Explorer` and `Windows>Settings` might be faster than resizing.

**Comment by samsinsane** [comment]
AB#322 has been completed and merged into master, this feature will be available in the next release.
