### ISSUE TITLE
Incomplete Chinese Translation

### ISSUE THREAD

**Issue by OsiJr** [Euclideon/vaultclient#129]
The following strings are currently not translated in master:

- View Shed (inc. all expanded options)
- Filter (inc. all expanded options)
- Euclideon Logo option
- License at login option
- Invert Mouse and Controller options
- Convert AllSpaceLabel
- Convert SpaceECEF
- Poly Model Mesh
- Poly Model Texture
- Poly Model Material Colour
- {polyModelInvertFaces}
- {scenePOIAttachModel}
- {scenePOIAttachModelURL}

**Comment by OsiJr** [comment]
Are you doing these @Hongzhi-liu?

**Comment by CarlCFX** [comment]
Also these:

- Oriented Image
- {polyModelInvertFaces}
- {scenePOIAttachModel}
- {scenePOIAttachModelURL}

**Comment by OsiJr** [comment]
@CarlCFX, could you get someone to check the latest master and see if this can be closed?

**Comment by samsinsane** [comment]
@OsiJr Did you intend to merge #138 before making this comment?

**Comment by OsiJr** [comment]
Yeah, I clicked merge but must have missed the step where I tell it that I really want to merge

**Comment by CarlCFX** [comment]
@OsiJr Looks like they are all in Client 0.4.0.19110607

**Comment by samsinsane** [comment]
Closing this issue based on previous comment.
