### ISSUE TITLE
The Chinese translation can not displayed as we want.

### ISSUE THREAD

**Issue by YaoGuangyuan** [Euclideon/vaultclient#170]
My laptop installed Windows 7(Japanese language), when I start to debug through visual studio 2015, switch language to Chinese, the menu can not be displayed as we want. Do you have any idea?

By the way, I downloaded the vault client from https://earth.vault.euclideon.com/ , the Chinese translation work well!
![vault](https://user-images.githubusercontent.com/3347942/68823458-28c5ac00-06d7-11ea-9fb5-09c707954f46.PNG)

**Comment by samsinsane** [comment]
The process of loading the font takes significantly longer in debug, so we decided to reduce the available characters to just the minimum required for the English translation. You can temporarily change this code to view it in debug, however we won't accept PRs that modify this:
https://github.com/Euclideon/vaultclient/blob/7b2c929bf5d77f98e9414765520e84cdd9ac8dc8/src/main.cpp#L676-L709

**Comment by YaoGuangyuan** [comment]
Thanks @samsinsane , I closed it!
