### ISSUE TITLE
Do you have any plan to support set shader for each layer 

### ISSUE THREAD

**Issue by YaoGuangyuan** [Euclideon/vaultclient#172]
Now Vault can change [Display Mode] in Visualisation option, this will works for all layer.
If I want to display one layer using Colour, another using Intensity, I can't do that.
Do you have any plan to do that?

**Comment by OsiJr** [comment]
@YaoGuangyuan, this is already functional in the next release of VDK:
https://github.com/Euclideon/vaultclient/blob/master_vdk_0.5.0/src/vcRender.cpp#L1180

**Comment by YaoGuangyuan** [comment]
@OsiJr Great! Thanks Paul
