### ISSUE TITLE
Incorrect link in readme.md

### ISSUE THREAD

**Issue by donutFred** [Euclideon/vaultclient#2]
The link to the Euclideon Vault page is now https://www.euclideon.com/vault/

**Comment by OsiJr** [comment]
Thanks for letting us know!

**Comment by donutFred** [comment]
You actually haven't fixed it yet

**Comment by OsiJr** [comment]
This issue will be resolved when the next update is pushed to GitHub (which is when we open source the full application).

As noted in the readme, that label is applied so everyone is aware that it is fixed internally:
> fixed – When possible, we will mark issues that have been completed internally. Unfortunately we cannot say specifically when the next release that includes the change will be.
