### ISSUE TITLE
Ability to click on any point and find out its classification value (if any)

### ISSUE THREAD

**Issue by CodeWarrior99** [Euclideon/vaultclient#213]
**Is your feature request related to a problem? Please describe.**

When working with large LIDAR datasets it's quite common to find datasets that are contaminated with noisy data. 

Using tools like LASTools can help remove a lot of the noise but I often find that there is still a lot left over which can severely diminish the visual impact of the data (especially if the LIDAR is not colourized).

Having this feature to merely identify the classification of the noisy data or its return type could really help speed up the noisy data removal process.

Alternatively, it would be useful to have a tool that would allow you to draw a box/cube or draw a polyline fence around noisy data areas and then export the coordinates to a text file that could be used by LASTools to remove the noisy data falling inside of those regions. 

**Describe the solution you'd like**

Vault is great at showing you where the noisy data is but it may not be able to help you very much with figuring out the classification values associated with that data (depending on who acquired the data and how well they stuck to the classification system). Data from the surface of the sea or lakes is often a good example of data that usually escapes being filtered out as noise and looks pretty bad.

**Describe alternatives you've considered**

Tried using LASTools to help with the process.
It's very iterative and slow at the moment and is only made worse with larger datasets.

**Additional context**

**Comment by OsiJr** [comment]
![image](https://user-images.githubusercontent.com/9654665/70881912-d94a0700-2019-11ea-89fd-5f273acbb634.png)

I've had a local branch for this locally for a little while, I'll try submit it this afternoon.

**Comment by CodeWarrior99** [comment]
One other thing that could be a useful option during the conversation process from LAS to UDS:

Give the user the option to generate multiple UDS files instead of just one UDS file.

Each UDS file would then act like a "layer" in Autocad and could represent an individual:
- intensity value
- return value
- scan angle
- scan line flag
- classification value
- point source
- RGB values

The user can then load all of the UDS files into Vault and then turn them on/off individually in order to better determine whether the data that they contain is worth keeping or not.

I think that this could dramatically improve the speed and the reliability of the QC process for companies that carry out the acquisition of aerial lidar datasets.

**Comment by OsiJr** [comment]
This is in #290 but has not been accepted yet.

**Comment by OsiJr** [comment]
This is working with the voxel inspector tool.
