### ISSUE TITLE
Ability to use more keyboard keys to control the camera

### ISSUE THREAD

**Issue by CodeWarrior99** [Euclideon/vaultclient#215]
**Is your feature request related to a problem? Please describe.**

Yes, controlling the camera with the mouse can sometimes trigger the "highlighting" of the model to be activated. This is annoying when trying to record a screen capture video whilst flying through the dataset since it forces you to stop moving and click somewhere in the skybox or an area on the map tile that is empty of data.

Also, if the user wants to adjust the movement speed of the camera (say when you get closer to the ground and you want to slow things down) you have to stop pressing the W key and then adjust the movement speed with the mouse pointer. This is also a disruptive thing to do whilst making a screen capture recording.

**Describe the solution you'd like**

It would be great to at least have the option of using the arrow keys to control:
- the direction of the motion of the camera (up,down, left, right)
- control the speed of the movement through the model (using the + and - keys)

Lastly, if there was an "aircraft simulation mode" that would make pressing the left or right arrow key cause the camera to "roll" like an aircraft would also be useful for some situations.

**Describe alternatives you've considered**

I've tried all of the other available keyboard control keys.

**Additional context**

**Comment by samsinsane** [comment]
> It would be great to at least have the option of using the arrow keys to control:
> - the direction of the motion of the camera (up,down, left, right)

This can be achieved with the Key Bindings system (In the menu bar under System, or Ctrl+B) in the latest builds.

> - control the speed of the movement through the model (using the + and - keys)

This can be done via the scroll wheel (In the Settings window under Input & Controls), to my knowledge this works similar to how Geoverse does.

@OsiJr can probably provide more information on the roll mechanic.

**Comment by CodeWarrior99** [comment]
Thanks for the info about the key bindings - I will check them out.

The scroll wheel causes the camera to "jump" either forward or backward - it does not affect the move speed permanently. Allowing the user to control the move speed using the + and - keys would be nice and simple / smoother way to do it in my opinion.

**Comment by samsinsane** [comment]
> The scroll wheel causes the camera to "jump" either forward or backward - it does not affect the move speed permanently.

As I said you need to check the setting in Settings window under Input & Controls, it defaults to Zoom not Movement Speed. What you described, sounds like the Zoom mechanic.

**Comment by CodeWarrior99** [comment]
I will check the settings but what I am really asking for is that the use of the + / - keys be made to be "default" functionality like the ASDF keys.

**Comment by CodeWarrior99** [comment]
You are correct - there is a setting for what the mouse scroll does:
either "dolly" or "move speed".
I think having the mouse wheel just be "dolly" and let the + / - keys to control the move speed is far more intuitive and similar to how other software works.

**Comment by OsiJr** [comment]
#449 fixes this.
