### ISSUE TITLE
Applying individual intensity values to datasets loaded into the Scene window

### ISSUE THREAD

**Issue by CodeWarrior99** [Euclideon/vaultclient#217]
**Is your feature request related to a problem? Please describe.**

Yes, often LAS files will have different ranges of intensities from one project to the next. When adjacent projects are loaded into the same Scene window you will see a "patch work" effect. The existing options to play with the intensity scale affects all of the models displayed in the Scene window so it's impossible to tweak them individually to make all of them look good at the same time.

**Describe the solution you'd like**

Need the ability to select each model individually and adjust its intensity scale value independently of the other models that are also visible in the same scene window.

**Describe alternatives you've considered**

The only option is to go back to the original LAS files and re-map their intensities to a common scale (say 0 to 255) and then re-create the UDS files for each of them. This is extremely slow manual process and is made even harder if you have to re-download old datasets because you deleted them to free up disk space.

**Additional context**

**Comment by CodeWarrior99** [comment]
![Intensity differences](https://user-images.githubusercontent.com/42997998/71322652-697cc600-24ca-11ea-9b7b-f210e2c6f945.png)

**Comment by OsiJr** [comment]
This is now in master. Thanks for the request 😄
