### ISSUE TITLE
Unable to deselect a Model using ctrl+click

### ISSUE THREAD

**Issue by CarlCFX** [Euclideon/vaultclient#3]
**Describe the bug**
It has been observed that you are no longer able to deselect a Model using ctrl+click.

**Steps To Reproduce**
1. Load Client 43962 
2. Load a few UDS's 
3. Ctrl+click them in the Scene Explorer to select them 
4. Now ctrl+click them to deselect them 
5. Observe that it no longer works

**Expected behavior**
Ctrl+clicking Models should both select and deselect them.

**Desktop (please complete the following information):**
 - Platform: Windows
 - Version: 0.3.1.43962

**Comment by OsiJr** [comment]
This is tracked as AB#8

**Comment by CarlCFX** [comment]
This is still occurring in Client 44610.

**Comment by CarlCFX** [comment]
Sorry, didn't see why this got closed before. Closing as it is tracked elsewhere as OsiJr mentioned.
