### ISSUE TITLE
Waiting for render license ... license never comes

### ISSUE THREAD

**Issue by CodeWarrior99** [Euclideon/vaultclient#359]
**Describe the bug**

Cannot view local UDS models or any of the default ones listed under the Projects menu.

**Steps To Reproduce**

Start the software 
Login
Try to connect to any of the default cloud based UDS models under the projects menu.
Try to load a local UDS model by dragging it into the UI.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Platform: [e.g. Windows, iOS, Chrome]
 - Version: [e.g. 0.3.1.43800]

Windows 10 -
Latest version of Vault (0.5) as well as the previous version of Vault.

**Additional context**

**Comment by CodeWarrior99** [comment]
![waiting for license](https://user-images.githubusercontent.com/42997998/76074505-bfc2b680-5f9b-11ea-8e8b-5b3e5889a214.png)

**Comment by OsiJr** [comment]
This is fixed, correct?

**Comment by CodeWarrior99** [comment]
Yes, thanks :-)
