### ISSUE TITLE
Reading 0 points

### ISSUE THREAD

**Issue by CodeWarrior99** [Euclideon/vaultclient#6]
**Describe the bug**
Hello,

I tried to convert a small OBJ file as a test (see attached) which comes from a large dataset for the city of Helsinki.

The Helsinki data can be found here:
[https://bit.ly/2kzHjrh](url)

After hitting the convert button the conversion process doesn’t even start and sits at “reading … 0 points”:

**Expected behavior**
Conversion process should have read the file and eventually produced the UDS file.

**Desktop (please complete the following information):**
 - Platform:  Windows 10 Home
 - Version: EuclideonVaultClient_Windows_0.3.1.43800 

**Additional context**

![Reading-zero-points](https://user-images.githubusercontent.com/42997998/64524957-004cba80-d300-11e9-85a1-0818fa944cfb.png)
![Tile_+055_+000_L13_0](https://user-images.githubusercontent.com/42997998/64524958-004cba80-d300-11e9-8aeb-57e06d3955fd.jpg)

**Comment by OsiJr** [comment]
This dataset is working as expected in the RC for 0.4.0 (expect the geozone isn't supported currently)
