### ISSUE TITLE
i ran run create_project.bat and selected the mode,but nothing happened?   where is  the generated project files ? thanks

### ISSUE THREAD

**Issue by hay-001** [Euclideon/vaultclient#996]
i ran  create_project.bat and selected the mode,but nothing happened?   where is  the generated project files ? thanks

**Comment by samsinsane** [comment]
A `udStream.sln` should appear beside the `create_project.bat`, if it didn't, it's possible you haven't got all of the dependencies - try running `git submodule update --init --recursive` and then run `create_project.bat` again.

**Comment by hay-001** [comment]
i tried running git submodule update --init --recursive, it download some dependencies.but i run create_project.bat again,still nothing genenated.

**Comment by samsinsane** [comment]
Can you run `create_project.bat` from the command line, does it output any errors?

**Comment by hay-001** [comment]
Error: G:/vaultclient/premake5.lua:60: udSDK not installed correctly. (No UDSDK_HOME environment variable or --udSDK=[PATH] argument!)

**Comment by samsinsane** [comment]
I see, you'll need to get a copy of our udSDK and set the environment variable mentioned to that location.

**Comment by hay-001** [comment]
problem solved .thanks
